# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/sameer-man-shrestha/Linux_Unreal_Engine_5.6.1

TARGETS = \
	RPG_GAME-Android-DebugGame  \
	RPG_GAME-Android-Development  \
	RPG_GAME-Android-Shipping  \
	RPG_GAME-Linux-DebugGame  \
	RPG_GAME-Linux-Development  \
	RPG_GAME-Linux-Shipping  \
	RPG_GAME-LinuxArm64-DebugGame  \
	RPG_GAME-LinuxArm64-Development  \
	RPG_GAME-LinuxArm64-Shipping  \
	RPG_GAME \
	RPG_GAMEEditor-Linux-DebugGame  \
	RPG_GAMEEditor-Linux-Development  \
	RPG_GAMEEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend RPG_GAMEEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug RPG_GAMEEditor-Linux-Debug


RPG_GAME-Android-DebugGame:
	 $(BUILD) RPG_GAME Android DebugGame  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAME-Android-Development:
	 $(BUILD) RPG_GAME Android Development  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAME-Android-Shipping:
	 $(BUILD) RPG_GAME Android Shipping  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAME-Linux-DebugGame:
	 $(BUILD) RPG_GAME Linux DebugGame  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAME-Linux-Development:
	 $(BUILD) RPG_GAME Linux Development  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAME-Linux-Shipping:
	 $(BUILD) RPG_GAME Linux Shipping  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAME-LinuxArm64-DebugGame:
	 $(BUILD) RPG_GAME LinuxArm64 DebugGame  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAME-LinuxArm64-Development:
	 $(BUILD) RPG_GAME LinuxArm64 Development  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAME-LinuxArm64-Shipping:
	 $(BUILD) RPG_GAME LinuxArm64 Shipping  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAME: RPG_GAME-Linux-Development

RPG_GAMEEditor-Linux-DebugGame:
	 $(BUILD) RPG_GAMEEditor Linux DebugGame  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAMEEditor-Linux-Development:
	 $(BUILD) RPG_GAMEEditor Linux Development  -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" $(ARGS)

RPG_GAMEEditor: RPG_GAMEEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/sameer-man-shrestha/Documents/Unreal Projects/RPG_GAME/RPG_GAME.uproject" -Game 

.PHONY: $(TARGETS)
